name: update demo

on:
  workflow_dispatch:
  push:
    branches:
      - automate-update-gif

env:
  CLICOLOR_FORCE: "1"

jobs:
  update-demo:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - uses: charmbracelet/vhs-action@v1
        with:
          path: ./tapes/cli-demo.tape
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: charmbracelet/vhs-action@v1
        with:
          path: ./tapes/library-demo.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: update docs
          body: ${{ github.sha }}
          branch: docs/update
          branch-suffix: short-commit-hash
