name: update demo

on:
  workflow_dispatch:

env:
  CLICOLOR_FORCE: "1"

jobs:
  update-demo:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # to install ttyd and ffmpeg
      - uses: charmbracelet/vhs-action@v2
        with:
          version: v0.4.0 # NOTE: https://github.com/charmbracelet/vhs-action/issues/137
          path: ./tapes/cli/demo.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: update cli gif
        run: |
          for t in ./tapes/cli/*; do
            vhs < $t
          done
      - name: update library gif
        run: |
          for t in ./tapes/library/*; do
            vhs < $t
          done

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: update docs
          body: ${{ github.sha }}
          branch: docs/update
          branch-suffix: short-commit-hash
